sudo: false
dist: trusty
language: python
python:
  - 2.7
cache:
  pip: true
install:
  - pip install -r requirements.txt
  - cd "$HOME"
  - git clone https://github.com/berquist/obarasaika.git
  - export PYTHONPATH="$PYTHONPATH:$HOME"
script:
  - make test
