sudo: false
dist: trusty
language: python
python:
  - 2.7
cache:
  pip: true
install:
  - pip install -r requirements.txt
  - git clone https://github.com/berquist/obarasaika.git
before_script:
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"
script:
  - make test
