all: pyints-small pyints-medium pyints-large

pyints-small:
	python LiH_STO-3G_pyints.py --S --T --V --M

pyints-medium:
	python LiH_STO-3G_pyints.py --L_from_M --EF_from_V --J_KF

pyints-large:
	python LiH_STO-3G_pyints.py --EFG_from_EF_from_V --ERI

pyints-huge:
	python LiH_STO-3G_pyints.py --J2_KF
